steps:
  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pripy-393601/ci-cd-gin', '.']

  # push it to gcr
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pripy-393601/ci-cd-gin']

  # deploy it (it's failing)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gin-flask'
      - '--image=gcr.io/pripy-393601/ci-cd-gin:latest'
      - '--platform=gke'
      - '--region=us-east1'
      - '--allow-unauthenticated'
options:
  logging: NONE