steps:
  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/pripy-393601/gin-flask', '.']  # Change the image tag to "gin-flask"

  # push it to gcr
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pripy-393601/gin-flask']  # Change the image tag to "gin-flask"

  # deploy it to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'gin-cluster'  # Nome do cluster GKE
      - '--region=us-east1'  # Região do cluster GKE
      - '--project=pripy-393601'  # projeto no GCP

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/deployment.yaml'  # path para o manifesto kubernetes
    # Redirecionar a saída para um arquivo de log
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1'  # Substitua pela sua zona do GKE
      - 'CLOUDSDK_CONTAINER_CLUSTER=gin-cluster'  # Substitua pelo nome do seu cluster GKE

 # Apply Prometheus ConfigMap
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'prometheus-config.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1'  # Replace with your GKE zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=gin-cluster'  # Replace with your GKE cluster name
      
 # Apply Prometheus Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'prometheus-deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1'  # Replace with your GKE zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=gin-cluster'  # Replace with your GKE cluster name

options:
  logging: CLOUD_LOGGING_ONLY 
