apiVersion: apps/v1
kind: Deployment
metadata:
  name: gin-flask
spec:
  replicas: 1 # Número de réplicas (pods) do app
  selector:
    matchLabels:
      app: gin-flask
  template:
    metadata:
      labels:
        app: gin-flask
    spec:
      containers:
        - name: gin-flask
          image: gcr.io/pripy-393601/gin-flask #:v1.0.0 # imagem Docker do app
          ports:
            - containerPort: 5000 # Porta em que o aplicativo Flask está escutando
          imagePullPolicy: Always  # <-- Add this line to set the imagePullPolicy
          # Defina outras configurações do contêiner, como recursos (CPU, memória), variáveis de ambiente, etc.

apiVersion: v1
kind: Service
metadata:
  name: gin-flask-service
spec:
  selector:
    app: gin-flask
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000